version: '3.3'

services:
  node:
    build: .
    expose:
      - "3000"  # Keep it as is, since it's only exposed to Nginx
    depends_on:
      - ocpu
    networks:
      - my-network

  ocpu:
    image: frafortu/ocpu:v1.0.0
    expose:
      - "8004"  # Expose on 11764 for Nginx
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "11765:11765"    # Nginx listens on 11765
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
      - ocpu
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
