version: '3.8'

name: gevis

services:
  node:
    build: .
    expose:
      - "3000"
    depends_on:
      - ocpu
    networks:
      - my-network

  ocpu:
    image: frafortu/ocpu:v1.0.3
    expose:
      - "8004"
    ports:
      - "8004:8004"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
      - ocpu
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
